# Generated by Django 4.2.7 on 2025-09-02 11:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título automático gerado', max_length=200)),
                ('conversation_type', models.CharField(choices=[('workout_consultation', 'Consulta de Treino'), ('nutrition_advice', 'Orientação Nutricional'), ('progress_analysis', 'Análise de Progresso'), ('motivation_chat', 'Chat Motivacional'), ('technique_guidance', 'Orientação Técnica'), ('general_fitness', 'Fitness Geral')], default='general_fitness', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('paused', 'Pausada'), ('completed', 'Finalizada'), ('archived', 'Arquivada')], default='active', max_length=20)),
                ('user_goal_context', models.CharField(blank=True, help_text='Objetivo específico desta conversa', max_length=50, null=True)),
                ('current_focus', models.CharField(blank=True, help_text='Foco atual da discussão', max_length=100, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('ai_responses_count', models.PositiveIntegerField(default=0)),
                ('user_satisfaction_rating', models.FloatField(blank=True, help_text='Avaliação do usuário (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Conversa expira automaticamente', null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0, help_text='Tempo médio de resposta da IA em segundos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversa de Chat',
                'verbose_name_plural': 'Conversas de Chat',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuário'), ('ai', 'IA'), ('system', 'Sistema')], max_length=10)),
                ('content', models.TextField(help_text='Conteúdo da mensagem')),
                ('status', models.CharField(choices=[('sent', 'Enviada'), ('processing', 'Processando'), ('delivered', 'Entregue'), ('failed', 'Falhou'), ('retrying', 'Tentando Novamente')], default='sent', max_length=20)),
                ('intent_detected', models.CharField(blank=True, help_text='Intenção detectada pela IA', max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confiança da IA na resposta (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ai_model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, help_text='Tempo de resposta em milissegundos', null=True)),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Tokens consumidos', null=True)),
                ('user_reaction', models.CharField(blank=True, choices=[('helpful', 'Útil'), ('not_helpful', 'Não Útil'), ('excellent', 'Excelente'), ('needs_improvement', 'Precisa Melhorar')], max_length=20, null=True)),
                ('user_feedback', models.TextField(blank=True, help_text='Feedback detalhado do usuário', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('referenced_workout_id', models.PositiveIntegerField(blank=True, help_text='ID do treino referenciado', null=True)),
                ('referenced_exercise_id', models.PositiveIntegerField(blank=True, help_text='ID do exercício referenciado', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('conversations_started', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('ai_responses_received', models.PositiveIntegerField(default=0)),
                ('average_satisfaction_rating', models.FloatField(blank=True, null=True)),
                ('positive_feedback_count', models.PositiveIntegerField(default=0)),
                ('negative_feedback_count', models.PositiveIntegerField(default=0)),
                ('average_conversation_length', models.FloatField(default=0.0, help_text='Número médio de mensagens por conversa')),
                ('average_session_duration', models.FloatField(default=0.0, help_text='Duração média em minutos')),
                ('total_tokens_consumed', models.PositiveIntegerField(default=0)),
                ('average_ai_response_time', models.FloatField(default=0.0, help_text='Tempo médio em segundos')),
                ('ai_confidence_average', models.FloatField(blank=True, null=True)),
                ('most_common_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('workout_recommendations_given', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Métricas do Chat',
                'verbose_name_plural': 'Métricas do Chat',
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('user_profile', 'Perfil do Usuário'), ('workout_history', 'Histórico de Treinos'), ('preferences', 'Preferências'), ('progress_data', 'Dados de Progresso'), ('conversation_summary', 'Resumo da Conversa'), ('external_references', 'Referências Externas')], max_length=30)),
                ('context_key', models.CharField(help_text='Chave identificadora do contexto', max_length=100)),
                ('context_value', models.JSONField(help_text='Dados do contexto em formato JSON')),
                ('relevance_score', models.FloatField(default=1.0, help_text='Relevância deste contexto (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('expires_at', models.DateTimeField(blank=True, help_text='Quando este contexto expira', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_data', to='chatbot.conversation')),
            ],
            options={
                'verbose_name': 'Contexto do Chat',
                'verbose_name_plural': 'Contextos do Chat',
                'unique_together': {('conversation', 'context_type', 'context_key')},
            },
        ),
    ]
