# Generated by Django 4.2.7 on 2025-08-21 12:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo_utilizado', models.CharField(choices=[('content_based', 'Baseado em Conteúdo'), ('collaborative', 'Colaborativo'), ('hybrid', 'Híbrido'), ('ml_personalized', 'ML Personalizado')], max_length=20)),
                ('score_confianca', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('motivo_recomendacao', models.TextField(help_text='Explicação gerada por IA')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('aceita_pelo_usuario', models.BooleanField(blank=True, null=True)),
                ('data_aceite', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_recomendado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
            },
        ),
    ]
