# Generated by Django 4.2.7 on 2025-10-03 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_created_by_user_workout_is_personalized'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-data_geracao'], 'verbose_name': 'Recomendação', 'verbose_name_plural': 'Recomendações'},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='data_visualizacao',
            field=models.DateTimeField(blank=True, help_text='Quando o usuário visualizou a recomendação', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Data de expiração da recomendação (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='visualizada',
            field=models.BooleanField(default=False, help_text='Se o usuário visualizou a recomendação'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='aceita_pelo_usuario',
            field=models.BooleanField(blank=True, default=None, help_text='True=aceita, False=rejeitada, None=ainda não decidiu', null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='algoritmo_utilizado',
            field=models.CharField(choices=[('content_based', 'Baseado em Conteúdo'), ('collaborative', 'Colaborativo'), ('hybrid', 'Híbrido'), ('ml_personalized', 'ML Personalizado')], help_text='Algoritmo usado para gerar a recomendação', max_length=20),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='data_aceite',
            field=models.DateTimeField(blank=True, help_text='Quando o usuário aceitou/rejeitou', null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, help_text='Quando a recomendação foi gerada'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='motivo_recomendacao',
            field=models.TextField(help_text='Explicação gerada por IA do porquê desta recomendação'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='score_confianca',
            field=models.FloatField(help_text='Score de confiança da recomendação (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='usuario',
            field=models.ForeignKey(help_text='Usuário que recebeu a recomendação', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='workout_recomendado',
            field=models.ForeignKey(blank=True, help_text='Treino recomendado pela IA', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='workouts.workout'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['usuario', '-data_geracao'], name='recommendat_usuario_187653_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['aceita_pelo_usuario'], name='recommendat_aceita__9de491_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['visualizada'], name='recommendat_visuali_42ad1a_idx'),
        ),
    ]
