# Generated by Django 4.2.7 on 2025-10-13 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_age_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil do Usuário', 'verbose_name_plural': 'Perfis dos Usuários'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_pattern_analysis',
            field=models.DateTimeField(blank=True, help_text='Última atualização do padrão', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learned_training_pattern',
            field=models.JSONField(blank=True, default=dict, help_text='Padrão detectado automaticamente pelo sistema'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_rest_days_between_workouts',
            field=models.IntegerField(default=1, help_text='Dias de descanso entre treinos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_training_days',
            field=models.JSONField(blank=True, default=list, help_text='[0=Dom, 1=Seg, 2=Ter, 3=Qua, 4=Qui, 5=Sex, 6=Sáb]'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='training_frequency',
            field=models.IntegerField(default=3, help_text='Quantos dias por semana quer treinar', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
