# Generated by Django 4.2.7 on 2025-10-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='physical_limitations',
            field=models.TextField(blank=True, help_text='Quaisquer lesões, dores ou restrições físicas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_workout_time',
            field=models.CharField(choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite'), ('flexible', 'Flexível')], default='flexible', help_text='Período do dia preferido para treino', max_length=20),
        ),
    ]
