# Generated by Django 4.2.7 on 2025-08-29 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sent', models.IntegerField(default=0)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
                ('total_clicked', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('stats_by_type', models.JSONField(blank=True, default=dict)),
                ('best_engagement_hour', models.IntegerField(blank=True, null=True)),
                ('avg_time_to_read', models.DurationField(blank=True, null=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('preferred_frequency', models.CharField(blank=True, max_length=20, null=True)),
                ('engagement_score', models.FloatField(default=0.0, help_text='Score de 0-1 baseado no engajamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('title_template', models.CharField(help_text='Use {{variavel}} para placeholders', max_length=200)),
                ('message_template', models.TextField(help_text='Use {{variavel}} para placeholders')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('variables', models.JSONField(default=list, help_text='Lista de variáveis disponíveis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('workout_reminder', 'Lembrete de Treino'), ('progress_update', 'Atualização de Progresso'), ('achievement', 'Conquistas'), ('motivational', 'Mensagens Motivacionais'), ('system', 'Notificações do Sistema'), ('general', 'Geral')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='Horário preferido para notificações', null=True)),
                ('frequency', models.CharField(choices=[('instant', 'Instantâneo'), ('daily', 'Diário'), ('weekly', 'Semanal'), ('never', 'Nunca')], default='daily', max_length=20)),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Configurações personalizadas JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('clicked', 'Clicada'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('notification_type', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('template_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dados extras da notificação')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_d1d348_idx'), models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_8fa9d0_idx')],
            },
        ),
    ]
