# Generated by Django 4.2.7 on 2025-08-22 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['muscle_group', 'name']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='calories_per_minute',
            field=models.FloatField(blank=True, help_text='Calorias queimadas por minuto (estimativa)', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Iniciante'), ('intermediate', 'Intermediário'), ('advanced', 'Avançado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duração estimada em minutos', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment_needed',
            field=models.CharField(blank=True, help_text='Equipamentos necessários, separados por vírgula', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instruções passo a passo', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(blank=True, choices=[('chest', 'Peito'), ('back', 'Costas'), ('shoulders', 'Ombros'), ('arms', 'Braços'), ('legs', 'Pernas'), ('abs', 'Abdômen'), ('cardio', 'Cardio'), ('full_body', 'Corpo Inteiro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do vídeo demonstrativo', null=True),
        ),
    ]
