# Generated by Django 4.2.7 on 2025-10-03 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0002_alter_workout_options_alter_workoutsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalized_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_personalized',
            field=models.BooleanField(default=False),
        ),
    ]
