# Generated by Django 4.2.7 on 2025-10-13 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0003_workout_created_by_user_workout_is_personalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o treino foi deletado', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que deletou o treino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Se False, o treino foi deletado (soft delete)'),
        ),
    ]
