# Generated by Django 4.2.7 on 2025-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Sedentário'), ('light', 'Leve'), ('moderate', 'Moderado'), ('active', 'Ativo'), ('very_active', 'Muito Ativo')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='focus_areas',
            field=models.CharField(blank=True, help_text='Áreas de foco separadas por vírgula', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose_weight', 'Perder Peso'), ('gain_muscle', 'Ganhar Músculo'), ('maintain', 'Manter Forma'), ('endurance', 'Melhorar Resistência')], max_length=50, null=True),
        ),
    ]
