// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8rlU9wQheofqJC5uKUeWUd-0ijGWMcDA',
    appId: '1:907146506069:web:c6b149ccd56f28dbfbc9dc',
    messagingSenderId: '907146506069',
    projectId: 'fitaitcc',
    authDomain: 'fitaitcc.firebaseapp.com',
    storageBucket: 'fitaitcc.firebasestorage.app',
    measurementId: 'G-FEMQGZ7B9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArjw0SUOgocjIHYAEZgDmJYXYWR51-JLE',
    appId: '1:907146506069:android:f8e5d3259bd1c79dfbc9dc',
    messagingSenderId: '907146506069',
    projectId: 'fitaitcc',
    storageBucket: 'fitaitcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqt968EfA8wPuoBU3KbqrwfhVR-LZsq4E',
    appId: '1:907146506069:ios:a030187d3f491a73fbc9dc',
    messagingSenderId: '907146506069',
    projectId: 'fitaitcc',
    storageBucket: 'fitaitcc.firebasestorage.app',
    iosBundleId: 'com.example.fitaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqt968EfA8wPuoBU3KbqrwfhVR-LZsq4E',
    appId: '1:907146506069:ios:a030187d3f491a73fbc9dc',
    messagingSenderId: '907146506069',
    projectId: 'fitaitcc',
    storageBucket: 'fitaitcc.firebasestorage.app',
    iosBundleId: 'com.example.fitaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8rlU9wQheofqJC5uKUeWUd-0ijGWMcDA',
    appId: '1:907146506069:web:9c1341394ba9f0c4fbc9dc',
    messagingSenderId: '907146506069',
    projectId: 'fitaitcc',
    authDomain: 'fitaitcc.firebaseapp.com',
    storageBucket: 'fitaitcc.firebasestorage.app',
    measurementId: 'G-CBG9GL2ZRY',
  );
}
