name: fitai_app
description: FitAI - Seu personal trainer inteligente com IA

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# =======================================================
# 1. DEPENDÊNCIAS DE TEMPO DE EXECUÇÃO (RUNTIME)
# =======================================================
dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Network
  dio: ^5.3.2
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  crypto: ^3.0.3 # MOVÍ AQUI, POIS É USADO NO RUNTIME

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # VERSÃO 6.1.0 USADA (6.2.1 ESTAVA REPETIDA ABAIXO)
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.6.0 # MOVÍ AQUI

  # Navigation
  go_router: ^16.2.4

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.3.2

  # Charts and Graphs
  fl_chart: ^0.68.0

  # Utils
  intl: ^0.20.2
  firebase_core: ^4.1.1 
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^6.1.6
  http: ^1.5.0
  url_launcher: ^6.3.1
  url_launcher_web: ^2.3.3
  youtube_player_iframe: ^5.1.2
  provider: ^6.1.1
  
  

# =======================================================
# 2. DEPENDÊNCIAS DE DESENVOLVIMENTO (CODE GEN, TESTES)
# =======================================================
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^10.0.5

  # Testing
  mockito: ^5.4.2
  bloc_test: ^10.0.0

  # Linting
  flutter_lints: ^6.0.0

# =======================================================
# 3. CONFIGURAÇÃO FLUTTER
# =======================================================
flutter:
  # Esta linha deve ter DOIS ESPAÇOS de recuo
  uses-material-design: true

  # Assets
  assets:
    # Estes itens devem ter QUATRO ESPAÇOS de recuo
    - assets/images/
   
